### ISSUE TITLE
Restaurant site using HTML CSS

### ISSUE THREAD

**Issue by prajaviS** [GEEKSFORGEEKS-SRMIST-NCR/GEEKSFORGEEKS-SRMIST-NCR.github.io#6]

**Comment by prajaviS** [comment]
pls assign me this task under hacktoberfest

**Comment by Tanish2002** [comment]
What?
This is not a project submission repo and even Hacktoberfest isn't about that.

You can open issues about bugs you find in this repo(site), about things we can improve and then we can help you.

Thanks.
